includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml

way_num: 1
shot_num: 5
query_num: 15
episode_size: 1
train_episode: 600
test_episode: 300
workers: 1
epoch: 100

augment: true
augment_times: 1
augment_times_query: 1
augment_method: DeepBdcAugment

backbone:
  name: resnet12Bdc
  kwargs:
    reduce_dim: 640

classifier:
  name: DeepBDC
  kwargs: ~

pretrain_path: ./results/DeepBDC_Pretrain-miniImageNet--ravi-resnet12Bdc-5-1-Feb-08-2023-17-07-27/checkpoints/emb_func_best.pth

optimizer:
  kwargs:
    lr: 0.0001
    momentum: 0.9
    nesterov: true
    weight_decay: 0.0005
  name: SGD
  other: null

lr_scheduler:
  kwargs:
    gamma: 0.1
    milestones:
    - 40
    - 80
  name: MultiStepLR

save_part:
  - emb_func
  - cls_classifier