includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/Proto.yaml
  # - backbones/resnet18.yaml

n_gpu: 1
device_ids: 0
way_num: 5
shot_num: 5
query_num: 15
episode_size: 1
train_episode: 600
test_episode: 300
workers: 8
epoch: 100
batch_size: 128

backbone:
  name: vanillanet_6
  kwargs:
    is_flatten: True
    is_feature: False
    last_pool: True
