augment: true
augment_method: Brightness
augment_times: 1
augment_times_query: 1
backbone:
  kwargs:
    avg_pool: false
    is_feature: false
    is_flatten: false
    last_block_stride: 1
  name: resnet18
batch_size: 128
classifier:
  kwargs:
    feat_dim: 512
    feat_height: 3
    feat_width: 3
  name: RelationNet
data_root: E:/DeepLearning/data/DF20
dataloader_num: 1
deterministic: true
device_ids: 0
episode_size: 1
epoch: 100
image_size: 84
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/RelationNet.yaml
- backbones/resnet18.yaml
- headers/ssl.yaml
log_interval: 100
log_level: info
log_name: null
log_paramerter: false
lr_scheduler:
  kwargs:
    gamma: 0.5
    step_size: 20
  name: StepLR
n_gpu: 1
optimizer:
  kwargs:
    lr: 0.001
  name: Adam
  other: null
parallel_part:
- emb_func
port: 26345
pretrain_path: null
query_num: 15
rank: 0
result_root: ./FinalResults/Brightness
resume: false
save_interval: 10
save_part:
- emb_func
seed: 2147483647
shot_num: 5
ssl_lbda: 0.5
ssl_task: null
tag: null
tb_scale: 2.0
test_episode: 300
test_epoch: 5
test_query: 15
test_shot: 5
test_way: 5
train_episode: 600
use_memory: false
val_per_epoch: 1
warmup: 0
way_num: 5
workers: 4
