includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/ConvMNet.yaml
  - backbones/resnet18.yaml
  - headers/ssl.yaml

way_num: 5
shot_num: 5
query_num: 15
episode_size: 1
train_episode: 600
test_episode: 300
workers: 12
epoch: 100
augment_method: HorizontalFlip
result_root: ./FinalResults/HorizontalFlip
ssl_task: ~
# ssl_lbda: 0.2

classifier:
  name: ConvMNet
  kwargs:
    n_local: 441

backbone:
  name: resnet18
  kwargs:
    is_flatten: False
    avg_pool: False
    is_feature: False
    last_block_stride: 1

optimizer:
  name: 'Adam'
  kwargs:
    betas: [0.5, 0.9]
    lr: 0.001 

# backbone:
#   name: resnet12
#   kwargs:
#     maxpool_last2: False
#     is_flatten: False

# need to modify: core/model/backbone/resnet_18.py:114 stride=1
# backbone:
#   name: resnet18
#   kwargs:
#     is_flatten: False
#     avg_pool: False

#backbone:
#  name: WRN
#  kwargs:
#    depth: 28
#    widen_factor: 10
#    avg_pool: False
#    is_flatten: False
